### ISSUE TITLE
error while running the script

### ISSUE THREAD

**Issue by SaddamBInSyed** [Mohamed209/monitoring-social-distancing-CSRNet#1]
@Mohamed209 
thanks for your work.

I am getting the below error while runnng the script on my win10 pc ( cpu only) + pycharm

Traceback (most recent call last):
  File "C:/Users/saddam.h.SMARTV/Downloads/monitoring-social-distancing-CSRNet-master/monitoring-social-distancing-CSRNet-master/predict.py", line 2, in <module>
    model = CSRNet()
  File "C:\Users\saddam.h.SMARTV\Downloads\monitoring-social-distancing-CSRNet-master\monitoring-social-distancing-CSRNet-master\model\model.py", line 26, in __init__
    self.frontend.state_dict().items()[i][1].data[:] = mod.state_dict().items()[i][1].data[:]
TypeError: 'odict_items' object does not support indexing

please advise

**Comment by Mohamed209** [comment]
@SaddamBInSyed 
The repository is in very early stage of the development , it is still under construction , once I finish developing  , I will officially release it

**Comment by SaddamBInSyed** [comment]
Thanks for the response.

Looking forward to see the complete one.

Once again thanks

**Comment by Mohamed209** [comment]
@SaddamBInSyed check repo final results
